version: "2"
services:
  cleandev:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
     - ".:/vagrant"
    environment:
     - PYTHONDONTWRITEBYTECODE=true
     - NODE_PATH=/vagrant-dev/node_modules/
